--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: clientes_cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes_cliente (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    nuit character varying(50),
    celular character varying(50)
);


ALTER TABLE public.clientes_cliente OWNER TO postgres;

--
-- Name: clientes_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cotacoes_cotacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cotacoes_cotacao (
    id bigint NOT NULL,
    numero character varying(20),
    nome_cliente character varying(100) NOT NULL,
    nuit_cliente character varying(20),
    celular_cliente character varying(20),
    data timestamp with time zone NOT NULL
);


ALTER TABLE public.cotacoes_cotacao OWNER TO postgres;

--
-- Name: cotacoes_cotacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cotacoes_cotacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cotacoes_cotacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cotacoes_itemcotacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cotacoes_itemcotacao (
    id bigint NOT NULL,
    quantidade integer NOT NULL,
    tipo character varying(10) NOT NULL,
    cotacao_id bigint NOT NULL,
    produto_id bigint NOT NULL,
    CONSTRAINT cotacoes_itemcotacao_quantidade_check CHECK ((quantidade >= 0))
);


ALTER TABLE public.cotacoes_itemcotacao OWNER TO postgres;

--
-- Name: cotacoes_itemcotacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cotacoes_itemcotacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cotacoes_itemcotacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: produtos_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtos_categoria (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL
);


ALTER TABLE public.produtos_categoria OWNER TO postgres;

--
-- Name: produtos_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produtos_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtos_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produtos_produto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtos_produto (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    descricao text NOT NULL,
    preco_venda numeric(10,2),
    preco_aluguer numeric(10,2),
    pode_ser_vendido boolean NOT NULL,
    pode_ser_alugado boolean NOT NULL,
    activo boolean NOT NULL,
    categoria_id bigint
);


ALTER TABLE public.produtos_produto OWNER TO postgres;

--
-- Name: produtos_produto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produtos_produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtos_produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_stock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stock_stock (
    id bigint NOT NULL,
    quantidade integer NOT NULL,
    produto_id bigint NOT NULL,
    data_entrada timestamp with time zone NOT NULL,
    CONSTRAINT stock_stock_quantidade_check CHECK ((quantidade >= 0))
);


ALTER TABLE public.stock_stock OWNER TO postgres;

--
-- Name: stock_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.stock_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO postgres;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id integer,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO postgres;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaccoes_cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaccoes_cliente (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    nuit character varying(20),
    celular character varying(20)
);


ALTER TABLE public.transaccoes_cliente OWNER TO postgres;

--
-- Name: transaccoes_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaccoes_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaccoes_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaccoes_itemtransaccao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaccoes_itemtransaccao (
    id bigint NOT NULL,
    quantidade integer NOT NULL,
    tipo character varying(10) NOT NULL,
    produto_id bigint NOT NULL,
    transaccao_id bigint NOT NULL,
    CONSTRAINT transaccoes_itemtransaccao_quantidade_check CHECK ((quantidade >= 0))
);


ALTER TABLE public.transaccoes_itemtransaccao OWNER TO postgres;

--
-- Name: transaccoes_itemtransaccao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaccoes_itemtransaccao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaccoes_itemtransaccao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaccoes_transaccao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaccoes_transaccao (
    id bigint NOT NULL,
    numero character varying(20),
    data timestamp with time zone NOT NULL,
    tipo_pagamento character varying(20) NOT NULL,
    cliente_id bigint NOT NULL
);


ALTER TABLE public.transaccoes_transaccao OWNER TO postgres;

--
-- Name: transaccoes_transaccao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaccoes_transaccao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaccoes_transaccao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Token	7	add_token
26	Can change Token	7	change_token
27	Can delete Token	7	delete_token
28	Can view Token	7	view_token
29	Can add Token	8	add_tokenproxy
30	Can change Token	8	change_tokenproxy
31	Can delete Token	8	delete_tokenproxy
32	Can view Token	8	view_tokenproxy
33	Can add outstanding token	9	add_outstandingtoken
34	Can change outstanding token	9	change_outstandingtoken
35	Can delete outstanding token	9	delete_outstandingtoken
36	Can view outstanding token	9	view_outstandingtoken
37	Can add blacklisted token	10	add_blacklistedtoken
38	Can change blacklisted token	10	change_blacklistedtoken
39	Can delete blacklisted token	10	delete_blacklistedtoken
40	Can view blacklisted token	10	view_blacklistedtoken
41	Can add categoria	11	add_categoria
42	Can change categoria	11	change_categoria
43	Can delete categoria	11	delete_categoria
44	Can view categoria	11	view_categoria
45	Can add produto	12	add_produto
46	Can change produto	12	change_produto
47	Can delete produto	12	delete_produto
48	Can view produto	12	view_produto
49	Can add cliente	13	add_cliente
50	Can change cliente	13	change_cliente
51	Can delete cliente	13	delete_cliente
52	Can view cliente	13	view_cliente
53	Can add cliente	14	add_cliente
54	Can change cliente	14	change_cliente
55	Can delete cliente	14	delete_cliente
56	Can view cliente	14	view_cliente
57	Can add transaccao	15	add_transaccao
58	Can change transaccao	15	change_transaccao
59	Can delete transaccao	15	delete_transaccao
60	Can view transaccao	15	view_transaccao
61	Can add item transaccao	16	add_itemtransaccao
62	Can change item transaccao	16	change_itemtransaccao
63	Can delete item transaccao	16	delete_itemtransaccao
64	Can view item transaccao	16	view_itemtransaccao
65	Can add stock	17	add_stock
66	Can change stock	17	change_stock
67	Can delete stock	17	delete_stock
68	Can view stock	17	view_stock
69	Can add cotacao	18	add_cotacao
70	Can change cotacao	18	change_cotacao
71	Can delete cotacao	18	delete_cotacao
72	Can view cotacao	18	view_cotacao
73	Can add item cotacao	19	add_itemcotacao
74	Can change item cotacao	19	change_itemcotacao
75	Can delete item cotacao	19	delete_itemcotacao
76	Can view item cotacao	19	view_itemcotacao
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$qXs6tv4x9MhaDq4WtaQEHj$HkMPehupDJLjRwTGYB07Obu/v8loVqrAZ7GNyf9JoUU=	2025-08-01 12:40:32.464663+02	t	Samuel			bayala@bayala.com	t	t	2025-07-28 14:40:27.790822+02
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: clientes_cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clientes_cliente (id, nome, nuit, celular) FROM stdin;
\.


--
-- Data for Name: cotacoes_cotacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cotacoes_cotacao (id, numero, nome_cliente, nuit_cliente, celular_cliente, data) FROM stdin;
\.


--
-- Data for Name: cotacoes_itemcotacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cotacoes_itemcotacao (id, quantidade, tipo, cotacao_id, produto_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-08-01 12:42:46.188944+02	1	Máquinas Fotocopiadoras/Impressoras	1	[{"added": {}}]	11	1
2	2025-08-01 12:43:05.496081+02	2	Tonners	1	[{"added": {}}]	11	1
3	2025-08-01 12:43:38.380919+02	3	Drums	1	[{"added": {}}]	11	1
4	2025-08-01 12:44:16.810362+02	4	Acessórios	1	[{"added": {}}]	11	1
5	2025-08-01 12:45:28.195585+02	1	C400	1	[{"added": {}}]	12	1
6	2025-08-01 12:47:28.094609+02	2	C8170	1	[{"added": {}}]	12	1
7	2025-08-01 12:47:35.793505+02	1	C400	2	[{"changed": {"fields": ["Pode ser alugado"]}}]	12	1
8	2025-08-01 12:48:51.841254+02	3	B8170	1	[{"added": {}}]	12	1
9	2025-08-01 12:49:22.645539+02	4	C7125	1	[{"added": {}}]	12	1
10	2025-08-01 12:49:48.533526+02	5	B7125	1	[{"added": {}}]	12	1
11	2025-08-01 12:50:12.070686+02	6	C7025	1	[{"added": {}}]	12	1
12	2025-08-01 12:50:30.896092+02	7	C8030	1	[{"added": {}}]	12	1
13	2025-08-01 12:50:55.37806+02	8	C415	1	[{"added": {}}]	12	1
14	2025-08-01 12:51:14.311183+02	9	B310	1	[{"added": {}}]	12	1
15	2025-08-01 12:52:26.090245+02	10	C9225	1	[{"added": {}}]	12	1
16	2025-08-01 12:52:45.903736+02	11	V280	1	[{"added": {}}]	12	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	authtoken	token
8	authtoken	tokenproxy
9	token_blacklist	outstandingtoken
10	token_blacklist	blacklistedtoken
11	produtos	categoria
12	produtos	produto
13	clientes	cliente
14	transaccoes	cliente
15	transaccoes	transaccao
16	transaccoes	itemtransaccao
17	stock	stock
18	cotacoes	cotacao
19	cotacoes	itemcotacao
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-06-25 10:10:54.451344+02
2	auth	0001_initial	2025-06-25 10:10:54.737902+02
3	admin	0001_initial	2025-06-25 10:10:54.827805+02
4	admin	0002_logentry_remove_auto_add	2025-06-25 10:10:54.84089+02
5	admin	0003_logentry_add_action_flag_choices	2025-06-25 10:10:54.853272+02
6	contenttypes	0002_remove_content_type_name	2025-06-25 10:10:54.894353+02
7	auth	0002_alter_permission_name_max_length	2025-06-25 10:10:54.924467+02
8	auth	0003_alter_user_email_max_length	2025-06-25 10:10:54.939795+02
9	auth	0004_alter_user_username_opts	2025-06-25 10:10:54.958671+02
10	auth	0005_alter_user_last_login_null	2025-06-25 10:10:54.992222+02
11	auth	0006_require_contenttypes_0002	2025-06-25 10:10:55.002324+02
12	auth	0007_alter_validators_add_error_messages	2025-06-25 10:10:55.033037+02
13	auth	0008_alter_user_username_max_length	2025-06-25 10:10:55.100904+02
14	auth	0009_alter_user_last_name_max_length	2025-06-25 10:10:55.141778+02
15	auth	0010_alter_group_name_max_length	2025-06-25 10:10:55.165398+02
16	auth	0011_update_proxy_permissions	2025-06-25 10:10:55.187927+02
17	auth	0012_alter_user_first_name_max_length	2025-06-25 10:10:55.205896+02
18	authtoken	0001_initial	2025-06-25 10:10:55.239712+02
19	authtoken	0002_auto_20160226_1747	2025-06-25 10:10:55.287424+02
20	authtoken	0003_tokenproxy	2025-06-25 10:10:55.300636+02
21	authtoken	0004_alter_tokenproxy_options	2025-06-25 10:10:55.307549+02
22	clientes	0001_initial	2025-06-25 10:10:55.328106+02
23	produtos	0001_initial	2025-06-25 10:10:55.41822+02
25	sessions	0001_initial	2025-06-25 10:10:55.521813+02
26	stock	0001_initial	2025-06-25 10:10:55.543754+02
29	transaccoes	0002_alter_transaccao_tipo_pagamento	2025-06-26 09:11:27.38163+02
32	produtos	0002_remove_itemcotacao_cotacao_and_more	2025-06-27 02:50:44.583383+02
33	cotacoes	0001_initial	2025-06-27 03:56:44.939073+02
34	transaccoes	0001_initial	2025-06-27 06:14:05.731574+02
35	stock	0002_stock_data_entrada_alter_stock_produto_and_more	2025-06-27 07:02:49.252012+02
36	stock	0003_stock_estado	2025-06-27 10:31:43.054595+02
37	stock	0004_remove_stock_estado_alter_stock_data_entrada	2025-06-27 13:11:40.795132+02
38	stock	0005_alter_stock_produto_alter_stock_quantidade	2025-06-30 22:59:56.504029+02
39	stock	0006_alter_stock_produto	2025-06-30 23:11:44.338562+02
40	token_blacklist	0001_initial	2025-07-21 23:49:31.626674+02
41	token_blacklist	0002_outstandingtoken_jti_hex	2025-07-21 23:49:31.722386+02
42	token_blacklist	0003_auto_20171017_2007	2025-07-21 23:49:31.797051+02
43	token_blacklist	0004_auto_20171017_2013	2025-07-21 23:49:31.970741+02
44	token_blacklist	0005_remove_outstandingtoken_jti	2025-07-21 23:49:32.225561+02
45	token_blacklist	0006_auto_20171017_2113	2025-07-21 23:49:32.254655+02
46	token_blacklist	0007_auto_20171017_2214	2025-07-21 23:49:33.193932+02
47	token_blacklist	0008_migrate_to_bigautofield	2025-07-21 23:49:33.616662+02
48	token_blacklist	0010_fix_migrate_to_bigautofield	2025-07-21 23:49:33.941234+02
49	token_blacklist	0011_linearizes_history	2025-07-21 23:49:33.951049+02
50	token_blacklist	0012_alter_outstandingtoken_user	2025-07-21 23:49:34.026645+02
51	stock	0002_alter_stock_data_entrada_alter_stock_quantidade	2025-07-24 15:38:06.681775+02
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
cvfu7vuw1ad8skwfzc83pf8x7k3dt5b5	.eJxVjEEOwiAQRe_C2pBCYSgu3fcMzTAzStVAUtqV8e7apAvd_vfef6kJtzVPW5NlmlmdlVGn3y0hPaTsgO9YblVTLesyJ70r-qBNj5XleTncv4OMLX_rXgwFpiEJRXclxx1axEGsB9-H6BMwO4zQAYG3XmICyy5AQGeJTFTvD_4nOA0:1uh5Bk:SCzQPc3oIDUH5xlYAVIVBwxtqByfUCLCI1O0YU7lal8	2025-08-13 13:41:40.647443+02
ifltx9eytbq6slwkqr22i478v076ypus	.eJxVjEEOwiAQRe_C2pBCYSgu3fcMzTAzStVAUtqV8e7apAvd_vfef6kJtzVPW5NlmlmdlVGn3y0hPaTsgO9YblVTLesyJ70r-qBNj5XleTncv4OMLX_rXgwFpiEJRXclxx1axEGsB9-H6BMwO4zQAYG3XmICyy5AQGeJTFTvD_4nOA0:1uhnBg:q-wyGlNCkahR1dFoQ_Eeer3fTpUj-M9lTbva3U_ti4A	2025-08-15 12:40:32.637591+02
\.


--
-- Data for Name: produtos_categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.produtos_categoria (id, nome) FROM stdin;
1	Máquinas Fotocopiadoras/Impressoras
2	Tonners
3	Drums
4	Acessórios
\.


--
-- Data for Name: produtos_produto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.produtos_produto (id, nome, descricao, preco_venda, preco_aluguer, pode_ser_vendido, pode_ser_alugado, activo, categoria_id) FROM stdin;
2	C8170		650000.00	\N	t	f	t	1
1	C400		69000.00	\N	t	f	t	1
3	B8170		455000.00	\N	t	f	t	1
4	C7125		200000.00	\N	t	f	t	1
5	B7125		150000.00	\N	t	f	t	1
6	C7025		300000.00	\N	t	f	t	1
7	C8030		380000.00	\N	t	f	t	1
8	C415		175000.00	\N	t	f	t	1
9	B310		135000.00	\N	t	f	t	1
10	C9225		1600000.00	\N	t	f	t	1
11	V280		2230000.00	\N	t	f	t	1
\.


--
-- Data for Name: stock_stock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stock_stock (id, quantidade, produto_id, data_entrada) FROM stdin;
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTA2ODA5NSwiaWF0IjoxNzUzNzA4MDk1LCJqdGkiOiIzYjE3ODAzMDY3NGI0OTUxOTlmM2M0YWRhNjE4NDk5ZiIsInVzZXJfaWQiOjF9.r7qUbbki5dP5e6GVGpwCKD1ckbaHzxvNX2sVirigqLI	2025-07-28 15:08:15.718224+02	2035-07-26 15:08:15+02	1	3b178030674b495199f3c4ada618499f
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1MjkyNywiaWF0IjoxNzUzNzkyOTI3LCJqdGkiOiI2NDFkNzlhYjk2NTY0YjE4YmU1ODhlZGI0YzUwZmFlYiIsInVzZXJfaWQiOjF9.-ghIhQAAEsZN38cf0Z_mHkvaOTL1QtHXu_WeDy4LuX0	2025-07-29 14:42:07.903373+02	2035-07-27 14:42:07+02	1	641d79ab96564b18be588edb4c50faeb
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1MzI3OSwiaWF0IjoxNzUzNzkzMjc5LCJqdGkiOiJkNjViYTE5MzMyNzI0M2M3YjYxMGE3OWUyZjRmYmE3MSIsInVzZXJfaWQiOjF9.lfMwD_YRERgSK5rkrVSD3qO_pQEI6lRz8_48vgHRtrw	2025-07-29 14:47:59.230705+02	2035-07-27 14:47:59+02	1	d65ba193327243c7b610a79e2f4fba71
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1MzMzNywiaWF0IjoxNzUzNzkzMzM3LCJqdGkiOiJiNzQxNGU0Nzg4YWI0Mjk1OGZiZGNkMTgyY2NlZGFiZCIsInVzZXJfaWQiOjF9.1Cj8v9K_C1jxEYnTW6gcKwyCh2e6hBIbEpbDaQ2LNhY	2025-07-29 14:48:57.84299+02	2035-07-27 14:48:57+02	1	b7414e4788ab42958fbdcd182ccedabd
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1MzM4NywiaWF0IjoxNzUzNzkzMzg3LCJqdGkiOiI0ZWM3YmUzYjIxZDU0Y2U3OWQwYzUwMmY0ZTNlYTIzMCIsInVzZXJfaWQiOjF9.HbnyTCPr3i2hGHyVMBRy3OyqL8piQYrzgBhm36lKSxQ	2025-07-29 14:49:47.038285+02	2035-07-27 14:49:47+02	1	4ec7be3b21d54ce79d0c502f4e3ea230
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1Mzk4MCwiaWF0IjoxNzUzNzkzOTgwLCJqdGkiOiIyYWE0MzJhNzlmMDM0YTE2YjVhNTgzNWQxODEzMTkyYyIsInVzZXJfaWQiOjF9.MUn1X87_VV5mk9d6EZ9hT6fpmOjpTsnvpD2aQn0MDBs	2025-07-29 14:59:40.119258+02	2035-07-27 14:59:40+02	1	2aa432a79f034a16b5a5835d1813192c
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDA3NCwiaWF0IjoxNzUzNzk0MDc0LCJqdGkiOiI4YmI3YWNkOTMyYmQ0ZTU4YTdhYzU2YTFkNzkyZDAyZiIsInVzZXJfaWQiOjF9.3OB5yOlru2x3lJTX0cvfjFrlxTea4LlBwGC7ho5u_GM	2025-07-29 15:01:14.952001+02	2035-07-27 15:01:14+02	1	8bb7acd932bd4e58a7ac56a1d792d02f
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDA3NCwiaWF0IjoxNzUzNzk0MDc0LCJqdGkiOiIyMjM3Y2YxYWU3MGU0MmMxOGNmMGQxMGNiZDMyZjllZiIsInVzZXJfaWQiOjF9.b0oXVB96YoGJTxyY3Aom1nWZ5fBIJ4F2lk5k-DXRo8g	2025-07-29 15:01:14.413732+02	2035-07-27 15:01:14+02	1	2237cf1ae70e42c18cf0d10cbd32f9ef
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDA3NCwiaWF0IjoxNzUzNzk0MDc0LCJqdGkiOiJjOTE3NjJiN2I4Y2I0ZWViOThmNDRjNWEyN2IyYWRkOCIsInVzZXJfaWQiOjF9.LEngNuv_LTaYTaTIu34i2IcWlTVSK2B1dVOWn775Nho	2025-07-29 15:01:14.491039+02	2035-07-27 15:01:14+02	1	c91762b7b8cb4eeb98f44c5a27b2add8
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDEzMiwiaWF0IjoxNzUzNzk0MTMyLCJqdGkiOiIwMTFkM2EzNjRiZmM0MGM5YjI4MGQ5ODVkYWEyOWExZiIsInVzZXJfaWQiOjF9.5Dq1-yeGYyg9CDaK01IakmjmZcuvT-OKnXNoXJ-kjLQ	2025-07-29 15:02:12.755723+02	2035-07-27 15:02:12+02	1	011d3a364bfc40c9b280d985daa29a1f
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDI1MywiaWF0IjoxNzUzNzk0MjUzLCJqdGkiOiJiZDY5MmU4YjQzODc0MTVlOGE4ZTNkZjU1ODlhMTY1YiIsInVzZXJfaWQiOjF9.XR5D29-McOtnOEUyRnX4bqR8hE5Xr2xQClM9_8eKXYw	2025-07-29 15:04:13.434741+02	2035-07-27 15:04:13+02	1	bd692e8b4387415e8a8e3df5589a165b
12	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDI2MywiaWF0IjoxNzUzNzk0MjYzLCJqdGkiOiIyZTBhMmE3NzA3YTg0Yjk1YWJmNDA4ZWQ3MTIyMDU5OSIsInVzZXJfaWQiOjF9.TfJ5zwVVZ4Q3LSbwnVkfSpMrUeMfHYl7tvzqqLsfuaY	2025-07-29 15:04:23.933794+02	2035-07-27 15:04:23+02	1	2e0a2a7707a84b95abf408ed71220599
13	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDQxMSwiaWF0IjoxNzUzNzk0NDExLCJqdGkiOiJkZGU4OTUyM2RkYzg0NDkwYWI1Y2M5OWIzOGI3NTVlOCIsInVzZXJfaWQiOjF9.BQ1DWLFgLYZsZRWKLU2SFhR_mAwM28HhwWy4NgqNKEU	2025-07-29 15:06:51.564022+02	2035-07-27 15:06:51+02	1	dde89523ddc84490ab5cc99b38b755e8
14	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDQ0MCwiaWF0IjoxNzUzNzk0NDQwLCJqdGkiOiI5NWE4NTBmYWY1ZTM0YjhiOGJkYTUxOGZjYWNjODQyMiIsInVzZXJfaWQiOjF9.1jQb5e7tb-iuSxzTa9G0Sxzn-2lZz7ax2kv04Gg13LA	2025-07-29 15:07:20.326212+02	2035-07-27 15:07:20+02	1	95a850faf5e34b8b8bda518fcacc8422
15	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDQ2MSwiaWF0IjoxNzUzNzk0NDYxLCJqdGkiOiJhZmI2MWNhZDlmZmQ0Y2FjYWU4MzlmMTcxMzc3MThlZiIsInVzZXJfaWQiOjF9.1-RGi--_9ZfWU79vu2yjE3BZ_yhrjm8Cdy4FunJ5uv4	2025-07-29 15:07:41.179608+02	2035-07-27 15:07:41+02	1	afb61cad9ffd4cacae839f17137718ef
16	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NDQ2NywiaWF0IjoxNzUzNzk0NDY3LCJqdGkiOiIxYzY3YTlhOWFlYjE0NjU0YmUyOTAyNmMxOWRkYTQyZSIsInVzZXJfaWQiOjF9._5uLeKEzuCkV12tPGt6YtTimxIPvYWlj7dxgxJuKBpI	2025-07-29 15:07:47.331246+02	2035-07-27 15:07:47+02	1	1c67a9a9aeb14654be29026c19dda42e
17	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTE1NTUyNywiaWF0IjoxNzUzNzk1NTI3LCJqdGkiOiI0YzIyZjI4NGZiNjk0N2EyODc5ZjRmMTQ4YmVjNjNiYSIsInVzZXJfaWQiOjF9.xl_ijEWdcMfLZIEVlP53IvZ0NY0MjoKGoXs_Hf0t2xc	2025-07-29 15:25:27.778985+02	2035-07-27 15:25:27+02	1	4c22f284fb6947a2879f4f148bec63ba
19	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNDY3NiwiaWF0IjoxNzUzODc0Njc2LCJqdGkiOiI3MzczMTA2ZGU0N2Y0YTBkYWY3N2JiODdjOTM1NTIwNSIsInVzZXJfaWQiOjF9.usYm6jFtE7DkRlSX448AJRT4ahSBkz3NH3hDrhEfH2E	2025-07-30 13:24:36.872164+02	2035-07-28 13:24:36+02	1	7373106de47f4a0daf77bb87c9355205
21	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNDY3NywiaWF0IjoxNzUzODc0Njc3LCJqdGkiOiJjZjEwMzViMjA4YmM0NGNmOTQyNzMwZGM1ZWQxOWM2ZiIsInVzZXJfaWQiOjF9.7iFmCRlPHsE7VFS0NVvS638IpoXSOnGjsR0Un3Kuj9k	2025-07-30 13:24:37.398943+02	2035-07-28 13:24:37+02	1	cf1035b208bc44cf942730dc5ed19c6f
18	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNDY3OSwiaWF0IjoxNzUzODc0Njc5LCJqdGkiOiI1MjcxODcyNmYxNmM0YTU0YjQzOTZhNzQ1MDVhYTBmOCIsInVzZXJfaWQiOjF9.dCynZZItVJ50yff77UpO04zbm6xFxt0KCgAfqe8Pakk	2025-07-30 13:24:39.16866+02	2035-07-28 13:24:39+02	1	52718726f16c4a54b4396a74505aa0f8
22	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNDY3NywiaWF0IjoxNzUzODc0Njc3LCJqdGkiOiIzZmViM2JhMmI4OWY0NDE4YjU3YjVmNmY2MTY4MzdmZCIsInVzZXJfaWQiOjF9.UTQpQCPesFDnNyDUa73tOmumKGLUJYF3yfiER3sCCFU	2025-07-30 13:24:37.427215+02	2035-07-28 13:24:37+02	1	3feb3ba2b89f4418b57b5f6f616837fd
20	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNDY3NiwiaWF0IjoxNzUzODc0Njc2LCJqdGkiOiI4OTY0NzA2MTVmMzA0OTcyYjgzNGNiOTI1OGY3NjVhZSIsInVzZXJfaWQiOjF9.GNMGTY9THx0aV1MFUMrFvKZ-bMm9PWsQr5LCtYv8OMI	2025-07-30 13:24:36.650447+02	2035-07-28 13:24:36+02	1	896470615f304972b834cb9258f765ae
23	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNDY4MSwiaWF0IjoxNzUzODc0NjgxLCJqdGkiOiI4OTVmMjBmZGI2MGU0MDU4OGZkZjZmZjllNDRjZGU2NyIsInVzZXJfaWQiOjF9.mV0BvwrsET5oJ9vmgOn3aikhUWepP5-BZ_mVdZxCRZw	2025-07-30 13:24:41.742757+02	2035-07-28 13:24:41+02	1	895f20fdb60e40588fdf6ff9e44cde67
24	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNDY4NywiaWF0IjoxNzUzODc0Njg3LCJqdGkiOiI4OTY1ZWFiOWZiOTk0YmYyYjQzMjNkNTIwZGRiZTU5ZSIsInVzZXJfaWQiOjF9.ICPgCcdbX0tx0FbQPkSUmBQNcTQnZwomP7czElCbdNY	2025-07-30 13:24:47.780305+02	2035-07-28 13:24:47+02	1	8965eab9fb994bf2b4323d520ddbe59e
25	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNTkwOSwiaWF0IjoxNzUzODc1OTA5LCJqdGkiOiI4NmI0MTlmMmJmY2Q0Zjk2OTc2MzNkNGFjNTNhNzQ0ZCIsInVzZXJfaWQiOjF9.PJvQj_9Q_kAoGoMx6okZwn4Djxmoh7IOfVcf4rqxbPI	2025-07-30 13:45:09.772755+02	2035-07-28 13:45:09+02	1	86b419f2bfcd4f9697633d4ac53a744d
26	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNjAyNCwiaWF0IjoxNzUzODc2MDI0LCJqdGkiOiJlY2I4NWUzMDUyMzU0NGRlYTVjZmY2ODc4Y2FmMGJlOSIsInVzZXJfaWQiOjF9.s6sZhcX_gsnyRuZQ8i1jYsJxx1PYnSJ3r5tljmyGHpc	2025-07-30 13:47:04.210527+02	2035-07-28 13:47:04+02	1	ecb85e30523544dea5cff6878caf0be9
27	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MjA2OTIzNjMzMSwiaWF0IjoxNzUzODc2MzMxLCJqdGkiOiI1ODNjZmZkNzA2NDM0YzgzODJlYTY4MWRmYzA3YTgxMiIsInVzZXJfaWQiOjF9.ng4VCoOsBfEZXU6jiN0NRZbWQdwBE_uTu9Jc5SoWDM4	2025-07-30 13:52:11.713849+02	2035-07-28 13:52:11+02	1	583cffd706434c8382ea681dfc07a812
\.


--
-- Data for Name: transaccoes_cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaccoes_cliente (id, nome, nuit, celular) FROM stdin;
\.


--
-- Data for Name: transaccoes_itemtransaccao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaccoes_itemtransaccao (id, quantidade, tipo, produto_id, transaccao_id) FROM stdin;
\.


--
-- Data for Name: transaccoes_transaccao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaccoes_transaccao (id, numero, data, tipo_pagamento, cliente_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: clientes_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clientes_cliente_id_seq', 1, false);


--
-- Name: cotacoes_cotacao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cotacoes_cotacao_id_seq', 1, false);


--
-- Name: cotacoes_itemcotacao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cotacoes_itemcotacao_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 16, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 51, true);


--
-- Name: produtos_categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produtos_categoria_id_seq', 4, true);


--
-- Name: produtos_produto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produtos_produto_id_seq', 11, true);


--
-- Name: stock_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stock_stock_id_seq', 1, false);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, false);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 27, true);


--
-- Name: transaccoes_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaccoes_cliente_id_seq', 1, false);


--
-- Name: transaccoes_itemtransaccao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaccoes_itemtransaccao_id_seq', 1, false);


--
-- Name: transaccoes_transaccao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaccoes_transaccao_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: clientes_cliente clientes_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes_cliente
    ADD CONSTRAINT clientes_cliente_pkey PRIMARY KEY (id);


--
-- Name: cotacoes_cotacao cotacoes_cotacao_numero_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cotacoes_cotacao
    ADD CONSTRAINT cotacoes_cotacao_numero_key UNIQUE (numero);


--
-- Name: cotacoes_cotacao cotacoes_cotacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cotacoes_cotacao
    ADD CONSTRAINT cotacoes_cotacao_pkey PRIMARY KEY (id);


--
-- Name: cotacoes_itemcotacao cotacoes_itemcotacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cotacoes_itemcotacao
    ADD CONSTRAINT cotacoes_itemcotacao_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: produtos_categoria produtos_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtos_categoria
    ADD CONSTRAINT produtos_categoria_pkey PRIMARY KEY (id);


--
-- Name: produtos_produto produtos_produto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtos_produto
    ADD CONSTRAINT produtos_produto_pkey PRIMARY KEY (id);


--
-- Name: stock_stock stock_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_stock
    ADD CONSTRAINT stock_stock_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: transaccoes_cliente transaccoes_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaccoes_cliente
    ADD CONSTRAINT transaccoes_cliente_pkey PRIMARY KEY (id);


--
-- Name: transaccoes_itemtransaccao transaccoes_itemtransaccao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaccoes_itemtransaccao
    ADD CONSTRAINT transaccoes_itemtransaccao_pkey PRIMARY KEY (id);


--
-- Name: transaccoes_transaccao transaccoes_transaccao_numero_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaccoes_transaccao
    ADD CONSTRAINT transaccoes_transaccao_numero_key UNIQUE (numero);


--
-- Name: transaccoes_transaccao transaccoes_transaccao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaccoes_transaccao
    ADD CONSTRAINT transaccoes_transaccao_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: cotacoes_cotacao_numero_e1d89b89_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cotacoes_cotacao_numero_e1d89b89_like ON public.cotacoes_cotacao USING btree (numero varchar_pattern_ops);


--
-- Name: cotacoes_itemcotacao_cotacao_id_77612e0c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cotacoes_itemcotacao_cotacao_id_77612e0c ON public.cotacoes_itemcotacao USING btree (cotacao_id);


--
-- Name: cotacoes_itemcotacao_produto_id_bddd13cf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cotacoes_itemcotacao_produto_id_bddd13cf ON public.cotacoes_itemcotacao USING btree (produto_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: produtos_produto_categoria_id_4444949b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX produtos_produto_categoria_id_4444949b ON public.produtos_produto USING btree (categoria_id);


--
-- Name: stock_stock_produto_id_f023bf81; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX stock_stock_produto_id_f023bf81 ON public.stock_stock USING btree (produto_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: transaccoes_itemtransaccao_produto_id_1d3d3fd7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX transaccoes_itemtransaccao_produto_id_1d3d3fd7 ON public.transaccoes_itemtransaccao USING btree (produto_id);


--
-- Name: transaccoes_itemtransaccao_transaccao_id_8f301391; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX transaccoes_itemtransaccao_transaccao_id_8f301391 ON public.transaccoes_itemtransaccao USING btree (transaccao_id);


--
-- Name: transaccoes_transaccao_cliente_id_98612021; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX transaccoes_transaccao_cliente_id_98612021 ON public.transaccoes_transaccao USING btree (cliente_id);


--
-- Name: transaccoes_transaccao_numero_f4f68c38_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX transaccoes_transaccao_numero_f4f68c38_like ON public.transaccoes_transaccao USING btree (numero varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cotacoes_itemcotacao cotacoes_itemcotacao_cotacao_id_77612e0c_fk_cotacoes_cotacao_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cotacoes_itemcotacao
    ADD CONSTRAINT cotacoes_itemcotacao_cotacao_id_77612e0c_fk_cotacoes_cotacao_id FOREIGN KEY (cotacao_id) REFERENCES public.cotacoes_cotacao(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cotacoes_itemcotacao cotacoes_itemcotacao_produto_id_bddd13cf_fk_produtos_produto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cotacoes_itemcotacao
    ADD CONSTRAINT cotacoes_itemcotacao_produto_id_bddd13cf_fk_produtos_produto_id FOREIGN KEY (produto_id) REFERENCES public.produtos_produto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: produtos_produto produtos_produto_categoria_id_4444949b_fk_produtos_categoria_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtos_produto
    ADD CONSTRAINT produtos_produto_categoria_id_4444949b_fk_produtos_categoria_id FOREIGN KEY (categoria_id) REFERENCES public.produtos_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stock_stock stock_stock_produto_id_f023bf81_fk_produtos_produto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_stock
    ADD CONSTRAINT stock_stock_produto_id_f023bf81_fk_produtos_produto_id FOREIGN KEY (produto_id) REFERENCES public.produtos_produto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaccoes_itemtransaccao transaccoes_itemtran_produto_id_1d3d3fd7_fk_produtos_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaccoes_itemtransaccao
    ADD CONSTRAINT transaccoes_itemtran_produto_id_1d3d3fd7_fk_produtos_ FOREIGN KEY (produto_id) REFERENCES public.produtos_produto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaccoes_itemtransaccao transaccoes_itemtran_transaccao_id_8f301391_fk_transacco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaccoes_itemtransaccao
    ADD CONSTRAINT transaccoes_itemtran_transaccao_id_8f301391_fk_transacco FOREIGN KEY (transaccao_id) REFERENCES public.transaccoes_transaccao(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaccoes_transaccao transaccoes_transacc_cliente_id_98612021_fk_transacco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaccoes_transaccao
    ADD CONSTRAINT transaccoes_transacc_cliente_id_98612021_fk_transacco FOREIGN KEY (cliente_id) REFERENCES public.transaccoes_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

