# Generated by Django 5.2.1 on 2025-06-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcotacao',
            name='cotacao',
        ),
        migrations.RemoveField(
            model_name='itemcotacao',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Cotacao',
        ),
        migrations.DeleteModel(
            name='ItemCotacao',
        ),
    ]
