# Generated by Django 5.2.1 on 2025-06-27 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_remove_itemcotacao_cotacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nuit', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo_pagamento', models.CharField(choices=[('mpesa', 'M-Pesa'), ('emola', 'E-Mola'), ('cheque', 'Cheque'), ('numerario', 'Numerário'), ('cartao', 'Cartão')], default='numerario', help_text='Tipo de pagamento usado na transacção', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccoes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransaccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('aluguer', 'Aluguer')], default='venda', max_length=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('transaccao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='transaccoes.transaccao')),
            ],
        ),
    ]
