# Generated by Django 5.2.1 on 2025-06-27 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_remove_itemcotacao_cotacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('nuit_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('aluguer', 'Aluguer')], default='venda', max_length=10)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cotacoes.cotacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
